### ISSUE TITLE
Using tree-sitter-languages get_languages("java") seeing: "TypeError: __init__() takes exactly 1 argument (2 given)"

### ISSUE THREAD

**Issue by jwmatthews** [jwmatthews/treesitter_example#1]
I am testing out usage of https://pypi.org/project/tree-sitter-languages/ to avoid building the language parser.
As I'm running a simple test I can't invoke [def get_language(language)](https://github.com/grantjenks/py-tree-sitter-languages/blob/42f4baffec92848be4937b0cc52b2872201fe322/tree_sitter_languages/core.pyx#L7)

Example
```
$ python3 java_scope_finder.py ./data/Example.java 7
Traceback (most recent call last):
  File "/Users/jmatthews/git/jwmatthews/treesitter_example/java_scope_finder.py", line 263, in <module>
    main()
  File "/Users/jmatthews/git/jwmatthews/treesitter_example/java_scope_finder.py", line 250, in main
    language = get_language('java')
               ^^^^^^^^^^^^^^^^^^^^
  File "tree_sitter_languages/core.pyx", line 14, in tree_sitter_languages.core.get_language
TypeError: __init__() takes exactly 1 argument (2 given)
```

Looks like tree-sitter-languages last release '1.10.2' is not compatible with a newer 'tree-sitter'.

Workaround I ended up with is to downgrade tree-sitter.

```
$ cat requirements.txt 
tree-sitter==0.21.3
tree-sitter-languages==1.10.2
```

**Comment by jwmatthews** [comment]
Related to https://github.com/grantjenks/py-tree-sitter-languages/issues/71
